name: Packer Workflow

on:
  workflow_dispatch:

jobs:
  setup_packer:
    runs-on: ubuntu-latest
    name: Build Packer image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: sudomateo/setup-packer@v1
        id: setup_packer
        with:
          packer-version: 'latest'

      - name: Print packer-version output
        run: echo "${{ steps.setup_packer.outputs.packer-version }}"

      - name: Run packer init
        run: packer init templates/test/test.pkr.hcl

      - name: Run packer build
        run: packer build -var "ClientID=${{ secrets.CLIENT_ID }}" -var "ClientSecret=${{ secrets.CLIENT_SECRET }}" -var "TenantId=${{ secrets.TENANT_ID }}" -var "SubscriptionId=${{ secrets.SUB_ID }}" -var "StorageAccountInstallersKey=${{ secrets.STORAGE_KEY }}" templates/test/test.pkr.hcl